[tool.poetry]
name = "hedgewig-textual"
version = "0.1.0"
description = ""
authors = ["woodFordR <adam@kaewell.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
textual = "^0.83.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
